### ISSUE TITLE
Daan: 10 commits via Terminal of Git Bash

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_nanos_2018#14]
[Hier](https://github.com/richelbilderbeek/djog_nanos_2018/graphs/contributors) kun je zien hoeveel commits je hebt gedaan. Heb je er tien, sluit dan deze Issue.

Tip: werk aan het sprookje, #2

**Comment by richelbilderbeek** [comment]
Goed gedaan! 31 commits!

Je kunt de Issue sluiten door 

 * Iets te zeggen, zoals 'Gelukt!'
 * Dan op 'Close and comment' te klikken

:+1:

**Comment by daantje1** [comment]
Klaar!
