### ISSUE TITLE
Daan: run 'keimooi' op jouw computer

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_nanos_2018#26]
Run het programma In de map 'team/richel/keimooi' (tip: doe 'Open Project', kies dan 'keimooi.pro') op jouw computer en maak een screenshot (tip: google op 'how to make a screenshot'), zoals deze:

![2019-01-23-164712_1920x1080_scrot](https://user-images.githubusercontent.com/2098230/51618435-9cbb7b80-1f2e-11e9-8c0a-8af2704162f0.png)

**Comment by daantje1** [comment]
Gelukt!
foto:
https://public.boxcloud.com/d/1/b1!yVgNBwXgLqhgR7FmpU3jqH_Ybs6Hmb6q6_Ofj3kWVDsNvZJaj0Ii-w653qA5FONd9NaATEHQv04qc0QmYKg1qp6Y_oSUO9fAMvBUXTJ6n9xxTTx0OY8Cxn_vKEpIRsjt-2QkppTeMTDwmN6-koWm_is3SxZKl2Aqq3fmH6dI-SmBRbRtQqckmTlcG-DPFNn9X_9KQcKj1MkSsicbj72g1CHgmC11882Q7M3hq9W-usPLMS3IbsVngbycmduT_nFshm0Rf-vGcPqZD9dNFBZnsnXTZQeH3FhHNTcrOH19nAwMbD6jD9xhZOeSBMzj3EVd5V2TYZFpUdomLQBQaMhEyYBst5j6xZqkw-Mi80hGgEgtMsx3EVAbXHq6ZDqF2AUg_zqQMJGi5KD2McDSjZOoW865JHP_52BGDTfe336TjCZCxWxoCmr4ECLxETvnvNkXiFHGC_UqtQHhxh_MX7WbOfo1i2zJ0sq1d4ZdiQLPCowPq9S-ZODegf0U7sYnXidS31wYbc-fSjH7suwtjxFspDJ6ckK7CPObHXlTvefjiuSX3fFWhKR-jHf52W6M2H9uBhOB4xagI7wFdPiOuHJrITrosXL4uZUAG33lgxHlpNt2Xy7BvoU6cnU-v00qClyuq0hhAO4-WtFizmb3EJBK4VtUFQn1DrRGNxbKP1Qi3BzQs6ZBxdFCsnct5IT17psgZQlfMG40EnaoO7Nnk3sgBz-_BBVaOSHJu6c7cPuZXQA4Fz1mTodN_HqDZ0nqEW-eGQxZPp5bZvfshaAN7qxhDje6nPhDW4gP295esp79el4k4JYp7buTpCmP7REWbhBrLiKZi2dQAGWkxz_5RsClUGkUtH6burJx_74tYHncmgdXcGx2q_bofpXFlklai0sVpRsxAa_GD8tv3xF1g5CVdTIlovl12YATkI7aA0umN2VjKL0OWB1ne3rAxHHJIesTJNK1gQyAUgPV3N_vBA-7lT5lbyUNitrZGta2VZmnPgCXl3-BVAR3dmGuci61GbNF02kyh3GvnMmzMdiSPLm0p3vgSQR5ZEW4N8DQ-98lrTmLKPLh2Qo0xrpMQbEnjtY7cWp3EU97cV5ID6AS2wIYNWtFZqZGUs7S87_mF5gna-Pi1vsfYFw0lL0Uws4Dsz6SO7I_qdMYcoZCjvXrWsZpIGpau6I5UzbuoDK02R_6xUHyYKbi3Lmpjqn4pvPlQUdipOm38GS_6f7iUrDQCmcDimAbDagcuCGGJHvGm4vD_o_u6XDGfDBFOmMECZM./download

**Comment by daantje1** [comment]
Gelukt!
foto:
https://public.boxcloud.com/d/1/b1!yVgNBwXgLqhgR7FmpU3jqH_Ybs6Hmb6q6_Ofj3kWVDsNvZJaj0Ii-w653qA5FONd9NaATEHQv04qc0QmYKg1qp6Y_oSUO9fAMvBUXTJ6n9xxTTx0OY8Cxn_vKEpIRsjt-2QkppTeMTDwmN6-koWm_is3SxZKl2Aqq3fmH6dI-SmBRbRtQqckmTlcG-DPFNn9X_9KQcKj1MkSsicbj72g1CHgmC11882Q7M3hq9W-usPLMS3IbsVngbycmduT_nFshm0Rf-vGcPqZD9dNFBZnsnXTZQeH3FhHNTcrOH19nAwMbD6jD9xhZOeSBMzj3EVd5V2TYZFpUdomLQBQaMhEyYBst5j6xZqkw-Mi80hGgEgtMsx3EVAbXHq6ZDqF2AUg_zqQMJGi5KD2McDSjZOoW865JHP_52BGDTfe336TjCZCxWxoCmr4ECLxETvnvNkXiFHGC_UqtQHhxh_MX7WbOfo1i2zJ0sq1d4ZdiQLPCowPq9S-ZODegf0U7sYnXidS31wYbc-fSjH7suwtjxFspDJ6ckK7CPObHXlTvefjiuSX3fFWhKR-jHf52W6M2H9uBhOB4xagI7wFdPiOuHJrITrosXL4uZUAG33lgxHlpNt2Xy7BvoU6cnU-v00qClyuq0hhAO4-WtFizmb3EJBK4VtUFQn1DrRGNxbKP1Qi3BzQs6ZBxdFCsnct5IT17psgZQlfMG40EnaoO7Nnk3sgBz-_BBVaOSHJu6c7cPuZXQA4Fz1mTodN_HqDZ0nqEW-eGQxZPp5bZvfshaAN7qxhDje6nPhDW4gP295esp79el4k4JYp7buTpCmP7REWbhBrLiKZi2dQAGWkxz_5RsClUGkUtH6burJx_74tYHncmgdXcGx2q_bofpXFlklai0sVpRsxAa_GD8tv3xF1g5CVdTIlovl12YATkI7aA0umN2VjKL0OWB1ne3rAxHHJIesTJNK1gQyAUgPV3N_vBA-7lT5lbyUNitrZGta2VZmnPgCXl3-BVAR3dmGuci61GbNF02kyh3GvnMmzMdiSPLm0p3vgSQR5ZEW4N8DQ-98lrTmLKPLh2Qo0xrpMQbEnjtY7cWp3EU97cV5ID6AS2wIYNWtFZqZGUs7S87_mF5gna-Pi1vsfYFw0lL0Uws4Dsz6SO7I_qdMYcoZCjvXrWsZpIGpau6I5UzbuoDK02R_6xUHyYKbi3Lmpjqn4pvPlQUdipOm38GS_6f7iUrDQCmcDimAbDagcuCGGJHvGm4vD_o_u6XDGfDBFOmMECZM./download

**Comment by richelbilderbeek** [comment]
Goed gedaan!

Tip: je kunt een screenshot maken met 'Print screen' (een toets op het toetsenbord) en dan in `mspaint` plakken met CTRL-V. Saven en hier op GitHub uploaden :+1:

**Comment by daantje1** [comment]
Heb ik ook gedaan hoor!

**Comment by daantje1** [comment]
kan het niet vinden. waar?

**Comment by richelbilderbeek** [comment]
![daar](https://user-images.githubusercontent.com/2098230/52002033-33ed7980-24c1-11e9-94b8-886c09c377ba.png)
