### ISSUE TITLE
Kloon deze repo op je harde schijf 

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_nanos_2018#3]
In Git Bash of terminal:

```
git clone https://github.com/richelbilderbeek/djog_nano_2018.git
```

Tip: je kunt de folder in met `cd djog_nanos_2018`

Deze Issue wordt gesloten als het hele team een commit heeft gedaan aan deze repo.

**Comment by jesperdoekes** [comment]
gedaan

**Comment by richelbilderbeek** [comment]
Naam|Gedaan?
---|---
Daan|
Jasper|
Jesper|Ja
Mees|
Oliver|
Richel|Ja
Seny|

**Comment by richelbilderbeek** [comment]
Staat nu bij 'Opstarten', dus ik kan deze Issue nu sluiten.
