### ISSUE TITLE
Start les 3: update code en doe 1 commit 

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_nanos_2018#36]
Om op te warmen in les 3, is de begindracht:

 * Update de code op je harde schijf
 * Maak een verandering, in bijvoorbeeld het sprookje
 * Push dit

Klaar? Zeg dat hieronder en haal jezelf uit de lijst van 'Assignees'

**Comment by ollyturner** [comment]
How do I go there?

**Comment by ollyturner** [comment]
@richelbilderbeek: spiek naar de 'git' uitleg op de hoofdpagina

**Comment by richelbilderbeek** [comment]
Klaar!

**Comment by rohangraaf** [comment]
gedaan

**Comment by rohangraaf** [comment]
gedaan

**Comment by rohangraaf** [comment]
gedaan

**Comment by rohangraaf** [comment]
gedaan

**Comment by ollyturner** [comment]
remote: Enumerating objects: 174, done.
remote: Counting objects: 100% (174/174), done.
remote: Compressing objects: 100% (122/122), done.
remote: Total 420 (delta 93), reused 103 (delta 41), pack-reused 246
Receiving objects: 100% (420/420), 2.57 MiB | 2.69 MiB/s, done.
Resolving deltas: 100% (242/242), completed with 6 local objects.
From https://github.com/richelbilderbeek/djog_nanos_2018
   6a491cb..983699a  master     -> origin/master
 * [new branch]      viewer     -> origin/viewer
Updating 6a491cb..983699a
Fast-forward
 README.md              |   4 +---
 auto_commit.md         |  11 +++++++++++
 doc/git.md             |  23 +++++++++++++++++++++--
 doc/git.pdf            | Bin 0 -> 29000 bytes
 plaatjes/cobra.gif     | Bin 0 -> 28338 bytes
 plaatjes/djo_gang.jpg  | Bin 0 -> 863443 bytes
 plaatjes/djo_hal.jpg   | Bin 0 -> 815369 bytes
 plaatjes/djo_trap.jpg  | Bin 0 -> 926542 bytes
 plaatjes/red_cobra.png | Bin 0 -> 13694 bytes
 scripts/ik_ben_richel  |   3 +++
 scripts/wie_ben_ik     |   5 +++++
 sprookje.md            |  42 +++++++++++++++++++++++++++++++++++++-----
 team/README.md         |   9 ++++++---
 team/daan/README.md    |  13 ++++++++++++-
 team/kyrill/README.md  |   3 +++
 team/quinn/README.md   |   3 +++
 team/rohan/README.md   |   3 +++
 17 files changed, 105 insertions(+), 14 deletions(-)
 create mode 100644 auto_commit.md
 create mode 100644 doc/git.pdf
 create mode 100644 plaatjes/cobra.gif
 create mode 100644 plaatjes/djo_gang.jpg
 create mode 100644 plaatjes/djo_hal.jpg
 create mode 100644 plaatjes/djo_trap.jpg
 create mode 100644 plaatjes/red_cobra.png
 create mode 100644 scripts/ik_ben_richel
 create mode 100644 scripts/wie_ben_ik
 create mode 100644 team/kyrill/README.md
 create mode 100644 team/quinn/README.md
 create mode 100644 team/rohan/README.md
huh?

**Comment by RedKnife47** [comment]
yeet done

**Comment by RedKnife47** [comment]
:]

**Comment by ollyturner** [comment]
done you people B]8]

**Comment by S3NY7** [comment]
klaar!

**Comment by mixmastermees** [comment]
claaaaaaaaaaaaaaaaaaaaaaaaaaar
