### ISSUE TITLE
Maak screenshot van Qt Creator

### ISSUE THREAD

**Issue by QuintinoM2** [richelbilderbeek/djog_nanos_2018#38]
Richel was mij vergeten. Dat is prima, ik was ook iets
later in het team. Hier een screenshot.
![screenshot_qt_creator](https://user-images.githubusercontent.com/47005675/52072587-8ee8a480-2585-11e9-8e66-b79e52146a3d.png)

**Comment by ollyturner** [comment]
![athing](https://user-images.githubusercontent.com/46792585/52074844-1684e200-258b-11e9-85ee-5c33bea86da7.png)

**Comment by ollyturner** [comment]
done you

**Comment by ollyturner** [comment]
wow
