### ISSUE TITLE
Installeer git

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_nanos_2018#4]
Je hebt git nodig:

 * Op Windows: download Git Bash, [https://git-scm.com/downloads](https://git-scm.com/downloads)
 * Op Linux:

```
sudo apt install git
```

 * Op Mac: ?

Deze Issue wordt gesloten als het hele team een commit heeft gedaan aan deze repo.

**Comment by S3NY7** [comment]
gedaan

**Comment by jesperdoekes** [comment]
ik ga dit niet nu doen

**Comment by richelbilderbeek** [comment]
Naam|Gedaan?
---|---
Daan|
Jasper|
Jesper|
Mees|
Oliver|
Richel|Ja
Seny|Ja

**Comment by richelbilderbeek** [comment]
Deze Issue staat nu beschreven bij 'doc/opstarten.md', dus ik kan 'm sluiten.
