### ISSUE TITLE
Aanpassing auto-commit

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_nanos_2018#41]
Ik vond het gaaf bestand 'auto_commit.md' te vinden, want het is goed bedacht :+1:

Er moeten wel wat dingen gebeuren:

 * [x] De copyright ('Niet aanpassen') is onmogelijk. Er zit een GPL-3 licensie op dit project, waarin staat dat dat juist wel mag. Verwijder de copyright of verwijder de hele tekst

  * [x] De tekst past beter in 'doc/git.md'. Verplaats de tekst naar dat bestand, verwijder dan 'auto_commit.md'

Goed gedaan en succes met deze klus :+1:

**Comment by daantje1** [comment]
Klaar
