### ISSUE TITLE
Start les 4: update code en doe 1 commit

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_nanos_2018#45]
Om op te warmen in les 4, is de begindracht:

 * Update de code op je harde schijf
 * Maak een verandering, in bijvoorbeeld het sprookje
 * Push dit

Klaar? Zeg dat hieronder en haal jezelf uit de lijst van 'Assignees'

**Comment by ollyturner** [comment]
Huh
