### ISSUE TITLE
wat voor adventure gaan we doen

### ISSUE THREAD

**Issue by mixmastermees** [richelbilderbeek/djog_nanos_2018#47]

**Comment by mixmastermees** [comment]
ik denk een klikker / je weetn wel game

**Comment by jesperdoekes** [comment]
kings quest

**Comment by mixmastermees** [comment]
het begind in big cookie city een paar vrienden(jack,henk,gert.lizzy.yonk) heben een cookie...(eigenlijk een gehijme organiezatie)
bakkerij maar dan word lizzy ont voerd

**Comment by richelbilderbeek** [comment]
King's Quest 4:

![kings_quest](https://user-images.githubusercontent.com/2098230/52441492-063bac80-2b21-11e9-91d8-3af5cb7f53d4.jpeg)

**Comment by richelbilderbeek** [comment]
Space Quest 3:

![space_quest_3](https://user-images.githubusercontent.com/2098230/52441528-24a1a800-2b21-11e9-88cf-996a65aba088.jpeg)

**Comment by richelbilderbeek** [comment]
Day Of The Tentacle:

![day_of_the_tentacle](https://user-images.githubusercontent.com/2098230/52441587-5581dd00-2b21-11e9-88ae-d959b216e896.png)

**Comment by richelbilderbeek** [comment]
Monkey Island:

![monkey_island](https://user-images.githubusercontent.com/2098230/52441772-de007d80-2b21-11e9-892f-df839f907a32.jpeg)

**Comment by richelbilderbeek** [comment]
Quest for Glory 2:

![quest_for_glory_2](https://user-images.githubusercontent.com/2098230/52441966-56ffd500-2b22-11e9-9c69-d14342adce5c.jpeg)

**Comment by richelbilderbeek** [comment]
Ik sluit deze, ik heb een beter idee...
