### ISSUE TITLE
Op jouw branch: maak een toevoeging aan het verhaal

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_nanos_2018#49]
Er is een bestand `verhaal.md` met het verhaal. Maak hier een toevoeging aan, **zonder merge conflicts**. 

Dus als je na `git pull` het woord `MERGE CONFLICT` ziet, open het bestand weer, maak het verhaal goed, en push opnieuw.

**Comment by QuintinoM2** [comment]
makkie'############################lolllllllllllllllll

**Comment by richelbilderbeek** [comment]
En nog een keer :+1:

**Comment by S3NY7** [comment]
gedaan

**Comment by richelbilderbeek** [comment]
We hebben nu een verhaal team. Ik sluit deze Issue.
