### ISSUE TITLE
git instellen

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_nanos_2018#5]
Doe de volgende regels in Git Bash of terminal (vervang mijn email en username door het jouwe):

```
git config --global user.email "richel@richelbilderbeek.nl"
git config --global user.name "richelbilderbeek"
```

Alleen voor mensen met Linux:

```
git config --global credential.helper cache
git config --global credential.helper 'cache --timeout=36000'
```

Hiermee hoef je je wachtwoord maar eens per 10 uur in te vullen. Of tot je je computer uitzet.

Deze Issue wordt gesloten als het hele team een commit heeft gedaan aan deze repo.

**Comment by jesperdoekes** [comment]
gedaan

**Comment by richelbilderbeek** [comment]
Naam|Gedaan?
---|---
Daan|
Jasper|
Jesper|Ja
Mees|
Oliver|
Richel|Ja
Seny|

**Comment by richelbilderbeek** [comment]
Nah, is niet belangrijk genoeg meer om open te houden. Het staat nu bij 'Opstarten'. 

Ik sluit deze Issue.
