### ISSUE TITLE
Op jouw branch: richt je eigen kamer in

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_nanos_2018#50]
Iedereen heeft een eigen kamer in de game. Maak deze mooi

**Comment by QuintinoM2** [comment]
makkelijk joh ########trolololololololololol

**Comment by jesperdoekes** [comment]
richel ik maak de garage en ik wou de garage tekennen, maar ik wist niet van welk perspectief ikdat moets tekennen. Ik kan het van de deur van binnen maar ook van buiten met een rol deur. Kun je me terug typen van welk perspectief ik het moet tekennen

**Comment by richelbilderbeek** [comment]
@jesperhd: vanuit het perspectief van de speler; zoals jij een garage ziet. Een voorbeeld van een slaapkamer hieronder: 

![slaapkamer_tekening](https://user-images.githubusercontent.com/2098230/55727241-db32e380-5a11-11e9-98ad-c23689873f7d.jpg)

Succes :+1:

**Comment by richelbilderbeek** [comment]
Genoeg geoefend, deze kan dicht.
