### ISSUE TITLE
Begin van elke les: merge develop naar jouw branch

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_nanos_2018#52]
DIt is het eerste dat we elke les doen.

Op [https://travis-ci.org/richelbilderbeek/djog_nanos_2018](https://travis-ci.org/richelbilderbeek/djog_nanos_2018) kun je zien of het je gelukt is.

Zie [de git documentatie](https://github.com/richelbilderbeek/djog_nanos_2018/blob/master/doc/git.md) hoe dit moet:

```
git checkout develop
git pull
git checkout richel
git merge develop
git push
```

Deze is Issue is nooit klaar: je hoeft deze nooit te sluiten of te verplaatsen :+1:

**Comment by S3NY7** [comment]
gedaan

**Comment by daantje1** [comment]
gedaan

**Comment by richelbilderbeek** [comment]
Ik heb er een note van gemaakt.
