### ISSUE TITLE
Jesper: Python scripts of in je eigen map, of weg

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_nanos_2018#54]
Ik vind [hier](https://github.com/richelbilderbeek/djog_nanos_2018/blob/master/1.py) een Python scriptje. Leuk, maar niet in onze hoofdfolder :grin: 

Zou je deze of kunnen verwijderen, of in je eigen folder doen (`team/jesper`)?

Dankjewel :+1:

**Comment by jesperdoekes** [comment]
opgelost door 10c2a397
