### ISSUE TITLE
Daan: verwijder viewer branch

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_nanos_2018#55]
Hoi Daan, 

ik zie op [Branches](https://github.com/richelbilderbeek/djog_nanos_2018/branches) dat jij een `viewer` branch gemaakt hebt. Als deze niet (meer) nodig hebt, zou jij deze weg kunnen halen?

Dankjewel :+1:

**Comment by daantje1** [comment]
klaar!
