### ISSUE TITLE
Helpen op Open Dag DJO op zaterdag 9 maart van 10:00-16:00?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_nanos_2018#56]
Op zaterdag 9 maart, van 10:00-16:00, heeft De Jonge Onderzoekers een Open Dag. Er komen dan veel kinderen en ouders op bezoek. 

Met Team Red Cobra (en [Team Octane](https://github.com/richelbilderbeek/djog_unos_2018/issues/394)) kunnen we lesgeven aan de bezoekers. Wat weet ik nog niet.

Je bent de hele dag welkom om te komen helpen. Als je korter kan, is dat ook prima! Wie doet er mee?

**Comment by daantje1** [comment]
als ik kan, dan kom ik!

**Comment by mixmastermees** [comment]
Ik ooook

Op do 21 feb. 2019 18:34 schreef daan <notifications@github.com>:

**Comment by QuintinoM2** [comment]
Ik wil wel maar ik kan niet :(:(:(:(:(:(:(:(:(:(:(:(:(:(:(

**Comment by S3NY7** [comment]
ik kom

**Comment by richelbilderbeek** [comment]
Gedaan! Goed gedaan kids :rainbow: :+1:
