### ISSUE TITLE
Meedoen met Pi Dag?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_nanos_2018#57]
Elk jaar wordt opnieuw moet [Pi Dag](http://richelbilderbeek.nl/RC_PiDay2015.htm) gevierd worden.

Elk jaar spreken we af op 13 Maart, om 23:57 (pi minuten voor middernacht, pi minuten voor Pi Dag), bij bushalte P op het Centraal Station in Groningen. Om 0:03 (pi minuten na middernacht) vertrekken we per voet en lopen we richting Grote Markt en terug. Onderweg stoepkrijten we pi symbolen op de grond.

Het is een rottijd op een doordeweekse dag, dus het is normaal dat ouders dit een slecht idee vinden. Sommige ouders brengen hun kind en doen dan gewoon mee :grin: 

Doe je mee? Laat het me hieronder weten!

**Comment by jesperdoekes** [comment]
Ik wil meee doen

**Comment by QuintinoM2** [comment]
ik wil meedoen maar ik weet nog niet of het van mijn ouders mag

**Comment by QuintinoM2** [comment]
ik wil meedoen maar ik weet nog niet of het van mijn ouders mag

**Comment by QuintinoM2** [comment]
ik wil meeeeeedoeoeoen maar ik weet niet of het van mijn ouders mag

**Comment by SuperProgaMaker** [comment]
hallo ik ben hier en dit is een lang berichtje en ook een **leuke tekst** ### lol  DIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIITTTTTTTTTTTTTTTTT IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIISSSSSSSSSSSSSS EEEEEEEEEEEEEEEENNNNNNNNNNNN LLLLLLLLLLLLLLLLLLLLAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNGGGGGGGGGGGGGGGGGGGG BBBBBBBBBBBBBBBBBBBBBBEEEEEEEEEEEEEEEEEEEEEEEEEEEERRRRRRRRRRRRRRRRRRRIIIIIIIIIIIIIIIIICCCCCCCCCCCCCHHHHHHHHHHHHHHHHHHTTTTTTTTTTTTTTJJJJJJJJJJJJJJJJJJJJJEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by SuperProgaMaker** [comment]
#test#

**Comment by S3NY7** [comment]
ik kan niet :(

**Comment by mixmastermees** [comment]
ik wil meeeeeeeeeeeeeeeeeeeee(s) doen

**Comment by rohangraaf** [comment]
ik mag !!!!!
(wel een scoutingkamp opgeoffert)
@richelbilderbeek

**Comment by QuintinoM2** [comment]
ik mag en mijn vader komt ook mee
:)

**Comment by QuintinoM2** [comment]
hoelang duurt het ongeveer

**Comment by richelbilderbeek** [comment]
Leuk!

Het duurt ongeveer een uur: we lopen naar de Grote Markt en weer terug (via een andere route) :rainbow:

**Comment by QuintinoM2** [comment]
Hoi Richel, dit is de moeder van Quinn even vanaf Quinns account :-) Ik vertelde een vriendin over vanavond en zij kent een journaliste die graag vanavond wil komen om een stukje te schrijven over Pi dag voor het Dagblad van het Noorden. Is dat goed? Kun je mij (Michelle) even je nummer mailen zodat ze je van tevoren kan bellen? Groetjes.

**Comment by richelbilderbeek** [comment]
Gelukt!

[We staan zelfs in de krant](https://www.dvhn.nl/groningen/Het-is-Pi-dag-Rich%C3%A8l-Bilderbeek-trekt-spoor-van-pis-door-Groninger-binnenstad-24265650.html)!

**Comment by richelbilderbeek** [comment]
[Radio fragment](https://www.rtvnoord.nl/radio/programma/20700/Karel-op-Noord/aflevering/22471) van 20:00-24:10

**Comment by richelbilderbeek** [comment]
[more news](https://www.rtvnoord.nl/nieuws/206075/Sinterklaas-vieren-we-alleen-op-aarde-pi-dag-kan-in-het-hele-universum)
