### ISSUE TITLE
fout repareren

### ISSUE THREAD

**Issue by jesperdoekes** [richelbilderbeek/djog_nanos_2018#62]
fout repareren

**Comment by jesperdoekes** [comment]
![Screenshot from 2019-03-20 16-24-22](https://user-images.githubusercontent.com/46792762/54696868-e2f71a80-4b2c-11e9-9185-551de0f11360.png)

**Comment by jesperdoekes** [comment]
ik wou gaan programeren en ik vond deze fout nou is het moeilijk om te programeren

**Comment by richelbilderbeek** [comment]
Jakkes, dat zijn verschillen tussen Qt4 en Qt5. Dankjewel @wdoekes om Jesper hierbij te helpen :+1:
