### ISSUE TITLE
opstarten moet een andere beschrijving krijgen

### ISSUE THREAD

**Issue by jesperdoekes** [richelbilderbeek/djog_nanos_2018#68]
![Screenshot from 2019-04-12 16-14-24](https://user-images.githubusercontent.com/46792762/56043707-13059800-5d3e-11e9-9453-3c73c58f05f8.png)

er staat dat we op 14 februari gaan bepalen of we doorgaan maar dat is al lang geweest

**Comment by jesperdoekes** [comment]
file:///home/jsvm/Pictures/Screenshot%20from%202019-04-12%2016-07-12.png

**Comment by jesperdoekes** [comment]
file:///home/jsvm/Pictures/Screenshot%20from%202019-04-12%2016-07-12.png

**Comment by richelbilderbeek** [comment]
Goed gezien! Ik pas het nu aan :+1:

**Comment by richelbilderbeek** [comment]
Veranderd, ik hoop dat je dit beter vind. Zo nee, dan zie ik wel een volgende Issue verschijnen :rainbow:
