### ISSUE TITLE
Wat voor game gaan we maken?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_nanos_2018#7]
We moeten beslissen welke game we gaan maken. 

De game moet:

 * in 2D zijn
 * werken met de widgets in Qt Creator
 * 31 januari: we zien wat Qt Creator kan, verzamelen stemmen
 * 7 februari: verzamelen stemmen tot 19:30, om 19:45 stemmen we welke game

**Comment by jesperdoekes** [comment]
schietgame

**Comment by mixmastermees** [comment]
clicker game

**Comment by S3NY7** [comment]
towerdefense slash shooter

**Comment by daantje1** [comment]
tetris-based game

**Comment by Brainlab009** [comment]
tower defense

**Comment by mixmastermees** [comment]
hack game
je moet iets hacken om $2M te verdienen de game is alleen met text 
er is ook een hack pollitie die moet voorkommen dat je de bank hackt en een groot drugs handel begint

**Comment by ollyturner** [comment]
A platformer game

**Comment by RafayelGardishyan** [comment]
Nature Zen achtig game!

**Comment by richelbilderbeek** [comment]
Horror/spannend tekstavontuur in De Jonge Onderzoekers!

Zork (enkel tekst):

![zork-i-758x426](https://user-images.githubusercontent.com/2098230/51615066-3d0da200-1f27-11e9-801b-6c1e59f1c91e.jpg)

City of Thieves (tekst en mooie GUI):

![gamecityofthievesdesktop](https://user-images.githubusercontent.com/2098230/51615065-3c750b80-1f27-11e9-9115-d24d8c5e850d.png)

Erik the Unready (tekst en mooie GUI en plaatje van elke locatie (fotocamera op DJO!): 

![erik](https://user-images.githubusercontent.com/2098230/51615064-3c750b80-1f27-11e9-8bd8-2ac8d08bac49.jpeg)

**Comment by mixmastermees** [comment]
hack game

**Comment by richelbilderbeek** [comment]
Carcasonne [zie Wikipedia](https://nl.wikipedia.org/wiki/Carcassonne_(spel)), maar dan simpeler.

![carcassonne_with_several_expansions](https://user-images.githubusercontent.com/2098230/52166112-68537680-2709-11e9-9f23-4a8a533f0292.jpg)

**Comment by richelbilderbeek** [comment]
Avonturenspel, zoals Maniac Mansion:

![maniacmansion](https://user-images.githubusercontent.com/2098230/52166207-81a8f280-270a-11e9-9226-d0553824c806.png)

**Comment by richelbilderbeek** [comment]
Hee, dit kan ook prima!

![dial_pong](https://user-images.githubusercontent.com/2098230/52416847-db366600-2aea-11e9-8149-9b294204297d.png)

**Comment by mixmastermees** [comment]
cola clikker

**Comment by mixmastermees** [comment]
space kliker

**Comment by mixmastermees** [comment]
raaar hoofd clikker

**Comment by mixmastermees** [comment]
k3 clikker

**Comment by mixmastermees** [comment]
muis klikker

**Comment by QuintinoM2** [comment]
richel clicker

**Comment by QuintinoM2** [comment]
red cobra clicker

**Comment by mixmastermees** [comment]
computer clikker

**Comment by QuintinoM2** [comment]
djog clicker

**Comment by mixmastermees** [comment]
toetssebord clikker

**Comment by QuintinoM2** [comment]
tegen offline mensen vechten game

**Comment by QuintinoM2** [comment]
loading game

**Comment by QuintinoM2** [comment]
mario kart

**Comment by jesperdoekes** [comment]
game of live game

**Comment by QuintinoM2** [comment]
super mario bros #like

**Comment by jesperdoekes** [comment]
tetris

**Comment by mixmastermees** [comment]
i head T pose game

**Comment by mixmastermees** [comment]
arcade

**Comment by QuintinoM2** [comment]
school staken game

**Comment by jesperdoekes** [comment]
een leuke game

**Comment by QuintinoM2** [comment]
virus download game

**Comment by mixmastermees** [comment]
pong)

**Comment by QuintinoM2** [comment]
pony ride game

**Comment by mixmastermees** [comment]
red cobra de game

**Comment by QuintinoM2** [comment]
wc game

**Comment by mixmastermees** [comment]
krijg jaspers jas uit game

**Comment by mixmastermees** [comment]
red cobra de game

**Comment by QuintinoM2** [comment]
richel is de beste game

**Comment by QuintinoM2** [comment]
game waar je een andere game in kan maken game

**Comment by QuintinoM2** [comment]
waterpark game

**Comment by mixmastermees** [comment]
programmeer game

**Comment by mixmastermees** [comment]
tel alle stemmen game

**Comment by QuintinoM2** [comment]
tel je rot game

**Comment by mixmastermees** [comment]
heel feeel tellen game

**Comment by mixmastermees** [comment]
i love k3 game

**Comment by QuintinoM2** [comment]
dik worden door pizza te eten game

**Comment by richelbilderbeek** [comment]
Deze Issue is no gesloten. We gaan zo stemmen,

**Comment by mixmastermees** [comment]
reken game keer sommen plus en min

**Comment by RedKnife47** [comment]
code kraken

**Comment by daantje1** [comment]
een command prompt zoals cmd

**Comment by richelbilderbeek** [comment]
Het is geworden: een adventure game!
