### ISSUE TITLE
Verwijder kelder

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_nanos_2018#71]
Er is besloten dat deze kamer niet meer nodig is. 

 * [x] Verwijder de header file (`.h`) van deze kamer
 * [x] Verwijder de implementation file (`.cpp`) van deze kamer
 * [x] Verwijder de user interface file (`.ui`) van deze kamer
 * [x] Verwijder deze kamer_soort uit `kamer_soort.h`
 * [x] Verwijder de #include van deze kamer in `hoofd_scherm.cpp`
 * [x] Verwijder de `addWidget` van deze kamer in `hoofd_scherm.cpp`

**Comment by daantje1** [comment]
Klaar! en nog snel ook :)
