### ISSUE TITLE
Inwerken Jonas

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_nanos_2018#80]
We hebben een nieuw lid: @jojojonie. Wie wil Jonas inwerken?

**Comment by richelbilderbeek** [comment]
Dit is nu genoeg gedaan, dat dit geen Issue meer is :+1:

**Comment by mixmastermees** [comment]
Is vandaag ook programmeren?


Op do 6 jun. 2019 15:42 schreef Richel Bilderbeek <notifications@github.com
