### ISSUE TITLE
Voeg kamer_soort::hal toe

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_nanos_2018#82]
:warning: iedereen doet een van dit soort Issue 'Voeg kamer_soort::iets toe' :warning: 

We hebben een hal, maar er bestaat geen `kamer_soort` met de naam `hal`.

 * [ ] Zoek naar de test bij deze Issue:

```c++
    //#define MAAK_ISSUE_82
    #ifdef MAAK_ISSUE_82
    static_assert(kamer_soort::hal, "");
    #endif // MAAK_ISSUE_82
```

Haal de commentaar van `//#define MAAK_ISSUE_82` weg.

Als het goed is, compiled het programma niet meer. Goed zo :+1: 

 * [ ] Voeg `hal` toe aan `enum class kamer_soort`. 

Als het goed is, compiled het programma nu weer!

 * [ ] Haal de troep weg

Haal de regels die beginnen met `#` weg. Dit zijn:

```c++
    //#define MAAK_ISSUE_82
```

en

```c++
    #ifdef MAAK_ISSUE_82
```

en

```c++
    #endif // MAAK_ISSUE_82
```

 * [ ] Inchecken! `git` add commit en push! Klaar :+1:

**Comment by jesperdoekes** [comment]
ik heb de kamer toegevoegt in 332a7abf7c1e6a42264e0d43c788f4d30c2ca9cc
