### ISSUE TITLE
Voeg kamer_soort::slaapkamer_ouders toe

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_nanos_2018#84]
:warning: iedereen doet een van dit soort Issue 'Voeg kamer_soort::iets toe' :warning:

We hebben een slaapkamer voor de ouders, maar er bestaat geen `kamer_slaapkamer_ouders` met de naam `lab`.

 * [ ] Zoek naar de test bij deze Issue:

```c++
    //#define MAAK_ISSUE_85
    #ifdef MAAK_ISSUE_85
    static_assert(kamer_soort::kamer_slaapkamer_ouders, "");
    #endif // MAAK_ISSUE_85
```

Haal de commentaar van `//#define MAAK_ISSUE_85` weg.

Als het goed is, compiled het programma niet meer. Goed zo :+1: 

 * [ ] Voeg `kamer_slaapkamer_ouders` toe aan `enum class kamer_soort`. 

Als het goed is, compiled het programma nu weer!

 * [ ] Haal de troep weg

Haal de regels die beginnen met `#` weg. Dit zijn:

```c++
    //#define MAAK_ISSUE_85
```

en

```c++
    #ifdef MAAK_ISSUE_85
```

en

```c++
    #endif // MAAK_ISSUE_85
```

 * [ ] Inchecken! `git` add commit en push! Klaar :+1:

**Comment by jesperdoekes** [comment]
ik heb de kamer toegevoegt in 332a7ab
