### ISSUE TITLE
Daan: promotie tot medior?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_nanos_2018#88]
Ik wil Daan graag medior maken. Een medior mag het werk van de topic branches mergen naar develop toe. Als develop dan stuk gaat, moet een medior dit zo snel als maar kan repareren. Ook moet een medior de junioren opleiden.

**Comment by richelbilderbeek** [comment]
@daantje1: goed plan?

Nee is prima, maar misschien vind je het wel gaaf :rainbow:

**Comment by daantje1** [comment]
Ja... vind ik goed!
